// Generates c64/glyphs.inc from src/glyphs.js and c64/font4x8.inc from
// src/font4x8.js.

import { writeFileSync } from 'node:fs';
import { CUSTOM_GLYPHS } from '../src/glyphs.js';
import { FONT4 } from '../src/font4x8.js';

const out = new URL('../../c64/glyphs.inc', import.meta.url);
const lines = [
  '; Generated by bridge/scripts/gen-glyphs.js - do not edit.',
  `NUM_GLYPHS = ${CUSTOM_GLYPHS.length}`,
  '',
  'glyph_slots:',
  ...CUSTOM_GLYPHS.map(([slot, ch]) => `        .byte ${slot}  ; ${ch}`),
  '',
  'glyph_data:',
];
for (const [slot, ch, rows] of CUSTOM_GLYPHS) {
  if (rows.length !== 8 || rows.some(r => !/^[#.]{8}$/.test(r))) throw new Error(`bad glyph ${slot} ${ch}`);
  lines.push(`        ; ${slot} ${ch}`);
  for (const r of rows) lines.push(`        .byte %${r.replace(/#/g, '1').replace(/\./g, '0')}`);
}
writeFileSync(out, lines.join('\n') + '\n');
console.log(`wrote ${out.pathname} (${CUSTOM_GLYPHS.length} glyphs)`);

// The soft 80-column client's 4x8 font: 8 bytes per screen code 0-127, each
// row in the high nibble.
const out4 = new URL('../../c64/font4x8.inc', import.meta.url);
const lines4 = ['; Generated by bridge/scripts/gen-glyphs.js from src/font4x8.js - do not edit.', '', 'font4:'];
FONT4.forEach((rows, code) => {
  lines4.push(`        .byte ${rows.map(r => '%' + (r << 4).toString(2).padStart(8, '0')).join(',')}  ; ${code}`);
});
writeFileSync(out4, lines4.join('\n') + '\n');
console.log(`wrote ${out4.pathname}`);
