// Generates c64/glyphs.inc from src/glyphs.js.

import { writeFileSync } from 'node:fs';
import { CUSTOM_GLYPHS } from '../src/glyphs.js';

const out = new URL('../../c64/glyphs.inc', import.meta.url);
const lines = [
  '; Generated by bridge/scripts/gen-glyphs.js - do not edit.',
  `NUM_GLYPHS = ${CUSTOM_GLYPHS.length}`,
  '',
  'glyph_slots:',
  ...CUSTOM_GLYPHS.map(([slot, ch]) => `        .byte ${slot}  ; ${ch}`),
  '',
  'glyph_data:',
];
for (const [slot, ch, rows] of CUSTOM_GLYPHS) {
  if (rows.length !== 8 || rows.some(r => !/^[#.]{8}$/.test(r))) throw new Error(`bad glyph ${slot} ${ch}`);
  lines.push(`        ; ${slot} ${ch}`);
  for (const r of rows) lines.push(`        .byte %${r.replace(/#/g, '1').replace(/\./g, '0')}`);
}
writeFileSync(out, lines.join('\n') + '\n');
console.log(`wrote ${out.pathname} (${CUSTOM_GLYPHS.length} glyphs)`);
